In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\harsh\Anaconda3\lib\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)
C:\Users\harsh\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [49]:
df = pd.read_csv('salary_data.csv')

In [50]:
df

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [51]:
X = df['YearsExperience']
y = df['Salary']
X.values.reshape((-1, 1))
y.values.reshape((-1, 1))
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=0)

In [52]:
print(train_x.shape)
print(test_x.shape)
print(train_y.shape)
print(test_y.shape)

(24,)
(6,)
(24,)
(6,)


In [53]:
train_x = train_x.values.reshape((-1, 1))
test_x = test_x.values.reshape((-1, 1))
train_y = train_y.values.reshape((-1, 1))
test_y = test_y.values.reshape((-1, 1))

In [54]:
print(train_x.shape)
print(test_x.shape)
print(train_y.shape)
print(test_y.shape)

(24, 1)
(6, 1)
(24, 1)
(6, 1)


In [73]:
model = LinearRegression()

In [74]:
model.fit(train_x, train_y)

LinearRegression()

In [75]:
y_pred = model.predict(test_x)

In [76]:
model.coef_

array([[9312.57512673]])

In [77]:
model.intercept_

array([26780.09915063])

In [78]:
mse = mean_squared_error(test_y, y_pred)
print("MSE:", mse)

MSE: 12823412.298126562


In [79]:
test_y

array([[ 37731],
       [122391],
       [ 57081],
       [ 63218],
       [116969],
       [109431]], dtype=int64)

In [80]:
y_pred

array([[ 40748.96184072],
       [122699.62295594],
       [ 64961.65717022],
       [ 63099.14214487],
       [115249.56285456],
       [107799.50275317]])

## Using pickle module

In [81]:
import pickle

In [82]:
with open("model_pickle", 'wb') as f:
    pickle.dump(model, f)

In [83]:
with open("model_pickle", 'rb') as f:
    mdl = pickle.load(f)

In [84]:
mdl.predict([[10]])

array([[119905.85041792]])

In [92]:
mdl.coef_

array([[9312.57512673]])

In [93]:
mdl.intercept_

array([26780.09915063])

## Using sklearn joblib
- using joblib is much more efficient

In [85]:
import joblib

In [86]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [87]:
mj = joblib.load('model_joblib')

In [89]:
mj.predict([[10]])

array([[119905.85041792]])

In [90]:
mj.coef_

array([[9312.57512673]])

In [91]:
mj.intercept_

array([26780.09915063])